    function renderWizard(){
      const body=document.getElementById('wizardBody'), foot=document.getElementById('wizardFoot');
      const total=6; document.getElementById('progressBar').style.width=`${Math.max(10,(wizard.step/total)*100)}%`;
      if(wizard.step===1){
        body.innerHTML=`<span class="eyebrow">Paso 1 de 6</span><h2 id="wizardTitle">¿Cómo querés empezar?</h2><p class="sub">Podés elegir un loteamiento o dejarnos guiarte según tus preferencias.</p><div class="options"><button class="option" onclick="wizard.project=null;wizard.city=null;choose('mode','guided')"><span>Quiero encontrar una opción según mi presupuesto</span><b>→</b></button>${projects.map(p=>`<button class="option" onclick="wizard.project='${p.name}';wizard.city='${p.city}';choose('mode','specific')"><span>Me interesa ${p.name}</span><b>→</b></button>`).join('')}</div>`;
      } else if(wizard.step===2){
        body.innerHTML=`<span class="eyebrow">Paso 2 de 6</span><h2 id="wizardTitle">${wizard.mode==='guided'?'¿Qué zona te resulta más conveniente?':'¿Qué rango de cuota estás considerando?'}</h2><p class="sub">${wizard.mode==='guided'?'Esto nos ayuda a orientar la consulta sin pedirte una ubicación exacta.':`Tomamos ${wizard.project} como interés inicial. Podés modificarlo después con el asesor.`}</p>${wizard.mode==='guided'?`<div class="options two"><button class="option ${selected('Yaguarón',wizard.city)}" onclick="choose('city','Yaguarón')">Yaguarón <b>→</b></button><button class="option ${selected('Itá',wizard.city)}" onclick="choose('city','Itá')">Itá <b>→</b></button><button class="option ${selected('Guarambaré',wizard.city)}" onclick="choose('city','Guarambaré')">Guarambaré <b>→</b></button><button class="option" onclick="choose('city','Quiero evaluar opciones')">Quiero evaluar opciones <b>→</b></button></div>`:budgetOptions()}`;
      } else if(wizard.step===3){
        if(wizard.mode==='guided') body.innerHTML=`<span class="eyebrow">Paso 3 de 6</span><h2 id="wizardTitle">¿Qué rango de cuota estás considerando?</h2><p class="sub">No es una solicitud de crédito ni una condición final; solo ayuda a orientar la conversación.</p>${budgetOptions()}`;
        else body.innerHTML=goalStep();
      } else if(wizard.step===4){
        body.innerHTML=wizard.mode==='guided'?goalStep():timingStep();
      } else if(wizard.step===5){
        body.innerHTML=wizard.mode==='guided'?timingStep():contactStep();
      } else if(wizard.step===6){
        body.innerHTML=wizard.mode==='guided'?contactStep():summaryStep();
      } else if(wizard.step===7){ body.innerHTML=summaryStep(); }
      if(wizard.step<=6 && !(wizard.step===6 && wizard.mode==='specific')) foot.innerHTML=`<button class="btn btn-light" onclick="backWizard()">← Anterior</button>${(wizard.mode==='guided'&&wizard.step===6)||(wizard.mode==='specific'&&wizard.step===5)?`<button class="btn btn-primary" onclick="saveContactAndContinue()">Revisar consulta →</button>`:''}`;
      else if((wizard.mode==='specific'&&wizard.step===6)||(wizard.mode==='guided'&&wizard.step===7)) foot.innerHTML=`<button class="btn btn-light" onclick="backWizard()">← Anterior</button><button class="btn btn-primary" onclick="submitLead()">Enviar consulta</button>`;
    }
    function budgetOptions(){return `<div class="options"><button class="option" onclick="choose('budget','Hasta Gs. 500.000')">Hasta Gs. 500.000 <b>→</b></button><button class="option" onclick="choose('budget','Gs. 500.000 a 1.000.000')">Gs. 500.000 a 1.000.000 <b>→</b></button><button class="option" onclick="choose('budget','Gs. 1.000.000 a 1.500.000')">Gs. 1.000.000 a 1.500.000 <b>→</b></button><button class="option" onclick="choose('budget','Quiero evaluar opciones')">Quiero evaluar opciones <b>→</b></button></div>`}
    function goalStep(){return `<span class="eyebrow">Paso ${wizard.mode==='guided'?4:3} de 6</span><h2 id="wizardTitle">¿Cuál es tu objetivo principal?</h2><p class="sub">La respuesta permite que el equipo entienda mejor el contexto de tu consulta.</p><div class="options two"><button class="option" onclick="choose('goal','Construir vivienda')">Construir vivienda <b>→</b></button><button class="option" onclick="choose('goal','Inversión')">Inversión <b>→</b></button><button class="option" onclick="choose('goal','Terreno familiar')">Terreno familiar <b>→</b></button><button class="option" onclick="choose('goal','Todavía no lo definí')">Todavía no lo definí <b>→</b></button></div>`}
    function timingStep(){return `<span class="eyebrow">Paso ${wizard.mode==='guided'?5:4} de 6</span><h2 id="wizardTitle">¿Cuándo te gustaría avanzar?</h2><p class="sub">No te compromete a comprar. Sirve para priorizar correctamente el seguimiento.</p><div class="options"><button class="option" onclick="choose('timing','Quiero avanzar pronto')">Quiero avanzar pronto <b>→</b></button><button class="option" onclick="choose('timing','Próximos 3 meses')">En los próximos 3 meses <b>→</b></button><button class="option" onclick="choose('timing','Próximos 6 meses')">En los próximos 6 meses <b>→</b></button><button class="option" onclick="choose('timing','Estoy explorando')">Solo estoy explorando <b>→</b></button></div>`}
    function contactStep(){return `<span class="eyebrow">Paso ${wizard.mode==='guided'?6:5} de 6</span><h2 id="wizardTitle">¿Dónde podemos contactarte?</h2><p class="sub">Con estos datos el equipo podría continuar la conversación con el contexto anterior.</p><div class="form-grid"><div class="field"><label for="leadName">Nombre y apellido *</label><input id="leadName" autocomplete="name" value="${esc(wizard.name)}" placeholder="Ej. Ana Gómez"></div><div class="field"><label for="leadPhone">WhatsApp / teléfono *</label><input id="leadPhone" inputmode="tel" autocomplete="tel" value="${esc(wizard.phone)}" placeholder="09XX XXX XXX"></div></div><div class="field"><label for="leadEmail">Email (opcional)</label><input id="leadEmail" type="email" autocomplete="email" value="${esc(wizard.email)}" placeholder="nombre@email.com"></div><div class="field"><label for="leadMessage">Comentario (opcional)</label><textarea id="leadMessage" placeholder="Algo que quieras agregar">${esc(wizard.message)}</textarea></div>`}
    function saveContactAndContinue(){
      const name=document.getElementById('leadName')?.value.trim(), phone=document.getElementById('leadPhone')?.value.trim();
      if(!name||!phone){toast('Completá nombre y teléfono para continuar.');return}
      wizard.name=name; wizard.phone=phone; wizard.email=document.getElementById('leadEmail').value.trim(); wizard.message=document.getElementById('leadMessage').value.trim(); wizard.step++; renderWizard();
    }
    function suggestedProject(){
      if(wizard.project)return wizard.project;
      const matches=projects.filter(p=>wizard.city==='Quiero evaluar opciones'||p.city===wizard.city);
      if(matches.length===1)return matches[0].name;
      if(wizard.budget==='Hasta Gs. 500.000') return matches.find(p=>p.name==='Guarapí'||p.name==='Mbaritu')?.name || matches[0]?.name || 'A definir con asesor';
      return matches[0]?.name || 'A definir con asesor';
    }
    function summaryStep(){wizard.project=suggestedProject();return `<span class="eyebrow">Revisión</span><h2 id="wizardTitle">Así llegaría tu consulta</h2><p class="sub">Podés volver atrás para modificar cualquier respuesta.</p><div class="summary-box"><div class="summary-row"><span>Interés inicial</span><strong>${esc(wizard.project)}</strong></div><div class="summary-row"><span>Zona</span><strong>${esc(wizard.city||'A definir')}</strong></div><div class="summary-row"><span>Rango</span><strong>${esc(wizard.budget||'A definir')}</strong></div><div class="summary-row"><span>Objetivo</span><strong>${esc(wizard.goal)}</strong></div><div class="summary-row"><span>Momento</span><strong>${esc(wizard.timing)}</strong></div><div class="summary-row"><span>Contacto</span><strong>${esc(wizard.name)} · ${esc(wizard.phone)}</strong></div></div>`}
