    function switchMode(mode){
      const client=mode==='client'; document.getElementById('clientView').classList.toggle('hidden',!client);document.getElementById('staffView').classList.toggle('hidden',client);
      document.getElementById('clientModeBtn').classList.toggle('active',client);document.getElementById('staffModeBtn').classList.toggle('active',!client);
      document.getElementById('clientModeBtn').setAttribute('aria-selected',client);document.getElementById('staffModeBtn').setAttribute('aria-selected',!client); if(!client)renderDashboard(); window.scrollTo({top:0,behavior:'smooth'});
    }
    document.getElementById('clientModeBtn').onclick=()=>switchMode('client');document.getElementById('staffModeBtn').onclick=()=>switchMode('staff');
    function badgeClass(s){return ({'Nuevo':'nuevo','Contactado':'contactado','Seguimiento':'seguimiento','Visita coordinada':'visita','Negociación':'negociacion'})[s]||''}
    function renderDashboard(){
      const counts={total:leads.length,nuevo:leads.filter(x=>x.status==='Nuevo').length,follow:leads.filter(x=>x.status==='Seguimiento').length,visit:leads.filter(x=>x.status==='Visita coordinada').length};
      document.getElementById('kpis').innerHTML=`<div class="kpi"><small>Oportunidades demo</small><strong>${counts.total}</strong><div class="delta">Incluye datos simulados</div></div><div class="kpi"><small>Nuevas</small><strong>${counts.nuevo}</strong><div class="delta">Estado demostrativo</div></div><div class="kpi"><small>En seguimiento</small><strong>${counts.follow}</strong><div class="delta">Estado demostrativo</div></div><div class="kpi"><small>Visita coordinada</small><strong>${counts.visit}</strong><div class="delta">Estado demostrativo</div></div>`; renderRows();
    }
    function renderRows(){
      const q=(document.getElementById('searchLead')?.value||'').toLowerCase(), status=document.getElementById('statusFilter')?.value||'';
      const filtered=leads.filter(l=>(!q||(l.name+' '+l.interest).toLowerCase().includes(q))&&(!status||l.status===status));
      document.getElementById('leadRows').innerHTML=filtered.length?filtered.map(l=>`<tr onclick="openLead('${l.id}')"><td class="person"><strong>${esc(l.name)}</strong><span>${esc(l.created)} · ${esc(l.id)}</span></td><td>${esc(l.interest)}</td><td>${esc(l.budget)}</td><td>${esc(l.timing)}</td><td><span class="badge ${badgeClass(l.status)}">${esc(l.status)}</span></td></tr>`).join(''):`<tr><td colspan="5" class="empty">No hay oportunidades con esos filtros.</td></tr>`;
    }
    document.getElementById('searchLead').addEventListener('input',renderRows);document.getElementById('statusFilter').addEventListener('change',renderRows);
    function openLead(id){activeLeadId=id;const l=leads.find(x=>x.id===id);if(!l)return;const overlay=document.getElementById('drawerOverlay');overlay.classList.remove('hidden');
      document.getElementById('leadDrawer').innerHTML=`<div class="drawer-head"><div><div class="drawer-brand"><img src="logo.svg" alt="IMCOPAR"></div><span class="demo-tag">Dato demostrativo</span><h2>${esc(l.name)}</h2><div style="color:var(--muted);font-size:.82rem">${esc(l.id)} · ${esc(l.created)}</div><div class="drawer-caption">Esta vista muestra cómo IMCOPAR podría recibir y seguir una consulta organizada.</div></div><button class="close" onclick="closeDrawer()">×</button></div><div class="drawer-body"><div class="drawer-grid"><div class="info-card"><small>Interés</small><strong>${esc(l.interest)}</strong></div><div class="info-card"><small>Objetivo</small><strong>${esc(l.goal)}</strong></div><div class="info-card"><small>Rango / cuota</small><strong>${esc(l.budget)}</strong></div><div class="info-card"><small>Momento</small><strong>${esc(l.timing)}</strong></div><div class="info-card"><small>Teléfono</small><strong>${esc(l.phone)}</strong></div><div class="info-card"><small>Email</small><strong>${esc(l.email)}</strong></div><div class="info-card"><small>Estado</small><strong>${esc(l.status)}</strong></div><div class="info-card"><small>Próxima acción</small><strong>${esc(l.followup||'Sin programar')}</strong></div></div><div class="activity"><h3>Actividad</h3><div class="timeline">${activityHtml(l)}</div></div><div class="action-intro">Usá las acciones de abajo para simular cómo el equipo podría cambiar el estado, registrar una nota o programar el próximo contacto.</div><div id="actionBox"></div></div><div class="drawer-actions"><button class="btn btn-dark" onclick="showStatusForm()">Cambiar estado</button><button class="btn btn-light" onclick="showNoteForm()">Agregar nota</button><button class="btn btn-light" onclick="showFollowForm()">Programar seguimiento</button></div>`;
    }
    function activityHtml(l){let events=[`<div class="event"><b>Oportunidad recibida</b><p>${esc(l.created)} · Origen: ${esc(l.source)}</p></div>`];l.notes.forEach(n=>events.push(`<div class="event"><b>Nota agregada</b><p>${esc(n)}</p></div>`));if(l.followup)events.push(`<div class="event"><b>Seguimiento programado</b><p>${esc(l.followup)}</p></div>`);if(l.status!=='Nuevo')events.push(`<div class="event"><b>Estado actual</b><p>${esc(l.status)}</p></div>`);return events.join('')}
    function drawerBackdrop(e){if(e.target.id==='drawerOverlay')closeDrawer()} function closeDrawer(){document.getElementById('drawerOverlay').classList.add('hidden');activeLeadId=null}
    function showStatusForm(){document.getElementById('actionBox').innerHTML=`<div class="action-form"><h4>Cambiar estado</h4><div class="field"><select id="newStatus"><option>Nuevo</option><option>Contactado</option><option>Seguimiento</option><option>Visita coordinada</option><option>Negociación</option></select></div><button class="btn btn-primary" onclick="updateStatus()">Guardar estado</button></div>`}
    function updateStatus(){const v=document.getElementById('newStatus').value,l=leads.find(x=>x.id===activeLeadId);l.status=v;persist();renderDashboard();openLead(activeLeadId);toast('Estado actualizado en la demo.')}
    function showNoteForm(){document.getElementById('actionBox').innerHTML=`<div class="action-form"><h4>Agregar nota</h4><div class="field"><textarea id="newNote" placeholder="Ej. Consultó por una visita al loteamiento"></textarea></div><button class="btn btn-primary" onclick="addNote()">Guardar nota</button></div>`}
    function addNote(){const v=document.getElementById('newNote').value.trim();if(!v){toast('Escribí una nota.');return}const l=leads.find(x=>x.id===activeLeadId);l.notes.unshift(v);persist();openLead(activeLeadId);toast('Nota agregada.')}
    function showFollowForm(){document.getElementById('actionBox').innerHTML=`<div class="action-form"><h4>Programar seguimiento</h4><div class="field"><label>Fecha y hora</label><input type="datetime-local" id="followDate"></div><button class="btn btn-primary" onclick="saveFollow()">Programar</button></div>`}
    function saveFollow(){const v=document.getElementById('followDate').value;if(!v){toast('Elegí una fecha y hora.');return}const d=new Date(v);const l=leads.find(x=>x.id===activeLeadId);l.followup=d.toLocaleString('es-PY',{dateStyle:'medium',timeStyle:'short'});if(l.status==='Nuevo')l.status='Seguimiento';persist();renderDashboard();openLead(activeLeadId);toast('Seguimiento programado.')}
    function resetDemo(){if(!confirm('¿Reiniciar la demo y volver a los datos demostrativos iniciales?'))return;localStorage.removeItem(STORAGE_KEY);leads=JSON.parse(JSON.stringify(seedLeads));persist();renderDashboard();closeDrawer();switchMode('staff');toast('Demo reiniciada.')}
    function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2300)}

    document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeWizard();closeDrawer()}});
    renderProjects();renderDashboard();
  